.github/workflows/build.ci.yml
.github/workflows/codeql.ci.yml
build.gradle.kts
buildSrc/src/main/kotlin/Versions.kt
gradle.properties
images/base/Dockerfile
images/builder/Dockerfile
packages/graalvm/build.gradle.kts
packages/rpc-jvm/build.gradle.kts
packages/server/build.gradle.kts
samples/fullstack/basic/server/build.gradle.kts
samples/fullstack/react-ssr/server/build.gradle.kts
samples/fullstack/react/server/build.gradle.kts
samples/fullstack/ssr/server/build.gradle.kts
samples/server/hellocss/build.gradle.kts
samples/server/helloworld/build.gradle.kts

This changeset upgrades the JDK version to 17. It will remain a draft for a brief time to allow for downstream testing.
Docker images (`base`, `builder`) will be tagged with `jdk17` to indicate support.
Changes enclosed:

Chore: Upgrade to Java 17

---

packages/server/src/main/kotlin/elide/server/controller/builtin/BuiltinController.kt
packages/server/src/main/kotlin/elide/server/controller/builtin/NotFoundController.kt
packages/server/src/main/kotlin/elide/server/controller/builtin/ServerErrorController.kt
packages/server/src/test/kotlin/elide/server/controller/builtin/BuiltinControllerTest.kt
packages/server/src/test/kotlin/elide/server/controller/builtin/NotFoundControllerTest.kt
packages/server/src/test/kotlin/elide/server/controller/builtin/ServerErrorControllerTest.kt

This changeset introduces the concept of _Built-in Handlers_, which are installed into the application context by default, and may be overridden at the developer's discretion.
These handlers are designed to implement baseline app functionality so that an out-of-the-box Elide app behaves as expected on the web.

Feature: Builtin Handlers

---

.github/labeler.yml
.github/workflows/build.ci.yml
.github/workflows/deploy.ci.yml

Adds a sub-workflow which can be dispatched generically to deploy an Elide sample or app.
Changes enclosed:
- Add deployment sub-workflow
- Use it from regular build

Feature: Deploys

---

.github/workflows/build.ci.yml
.github/workflows/labeler.ci.yml
kotlin-js-store/yarn.lock
packages/graalvm/build.gradle.kts
packages/graalvm/src/main/kotlin/elide/runtime/graalvm/JsRuntime.kt
packages/graalvm/src/main/kotlin/elide/runtime/graalvm/JsRuntimeFeature.kt
samples/fullstack/react-ssr/fly.toml
samples/fullstack/react-ssr/server/build.gradle.kts
samples/fullstack/react-ssr/server/src/main/resources/META-INF/native-image/reflect-config.json
samples/fullstack/react-ssr/server/src/main/resources/META-INF/native-image/resource-config.json

This changeset applies a fix to the React SSR sample for an error where `kotlin.random.Random` is missing.

Fix: Native SSR Sample

---

buildSrc/build.gradle.kts
gradle/loadProps.gradle
gradle/loadProps.gradle.kts
tools/substrate/buildSrc/build.gradle.kts

This is for consistency with all the other Gradle files.

Convert `loadProps.gradle` to Kotlin script

---

packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/JsProxy.kt
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressAppIntrinsic.kt
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressRequestIntrinsic.kt
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressResponseIntrinsic.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/express/ExpressApp.kt
packages/graalvm/src/main/kotlin/module-info.java
packages/graalvm/src/test/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressAppIntrinsicTest.kt
packages/graalvm/src/test/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressIntrinsicTest.kt

This PR improves Elide's Express.js feature:
* Middleware support including path-scoped handlers 🎉
* Request params are now writable (useful for parameter-mapping middleware)
* Request objects are now writable (useful for request-enhancing middleware)

feat: express middleware support

---

.devcontainer/Dockerfile
.devcontainer/buildless.yaml
.devcontainer/devcontainer.json
.devcontainer/init.gradle.kts

Improvements and bugfixes for the main devcontainer / codespace.
- feat: recommended `BUILDLESS_APIKEY` secret
- feat: pkgst proxy for java and go deps
- feat: auto-open `README.md` on codespace open
- chore: upgrade gvm → `20.0.2`
- chore: set minimum machine size spec

feat: updates to codespace

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/new_feature.yaml
.github/ISSUE_TEMPLATE/other.yaml

Adds issue templates to the Elide repository, which will be used in upcoming CLI features.

feat: add initial issue templates

---

tools/elide-build/build.gradle.kts
tools/elide-build/src/main/kotlin/elide/internal/conventions/ElideConventionPlugin.kt
tools/processor/build.gradle.kts

This PR amends the work from #414 on `javadoc` artifacts in Maven publications.

fix: avoid duplicate javadoc artifacts in publications.

---

packages/cli/build.gradle.kts
packages/cli/src/main/kotlin/elide/tool/cli/AbstractSubcommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt
packages/cli/src/main/kotlin/elide/tool/extensions/Intrinsics.kt
packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/IntrinsicsManager.kt
packages/runtime-core/api/runtime-core.api
packages/runtime-core/src/main/kotlin/elide/runtime/core/HostPlatform.kt
packages/runtime-core/src/main/kotlin/elide/runtime/core/PolyglotContext.kt
packages/runtime-core/src/main/kotlin/elide/runtime/core/extensions/ExecutionListener.kt
packages/runtime-core/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMContext.kt
packages/runtime-core/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMEngine.kt
packages/runtime-core/src/main/kotlin/elide/runtime/plugins/AbstractLanguageConfig.kt
packages/runtime-core/src/main/kotlin/elide/runtime/plugins/debug/DebugConfig.kt
packages/runtime-core/src/main/kotlin/elide/runtime/plugins/debug/DebugPlugin.kt
packages/runtime-js/src/main/kotlin/elide/runtime/plugins/js/JavaScript.kt

This PR adopts the new runtime configuration API in the Elide CLI, and introduces some additional changes to the `runtime-core` module to support this migration:
- New `Debug` engine plugin, used to configure inspection and debugging options.
- GraalVM execution listeners can now be attached to a `PolyglotEngine` using an extension, without accessing the underlying GraalVM Engine.
- New `PolyglotContext.parse` method (mirroring the `Context.parse` method in GraalVM's API).
- The `JavaScript` runtime language plugin now correctly applies WASM-related options.
- A bug in the `AbstractLanguageConfig` class was fixed; it prevented language bindings from being applied correctly.

feat(cli): use new DSL API for context acquisition.

---

package.json
packages/cli/src/main/kotlin/elide/tool/cli/AbstractSubcommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/ElideTool.kt
packages/cli/src/main/kotlin/elide/tool/engine/NativeEngine.kt
packages/cli/src/main/kotlin/elide/tool/io/RuntimeWorkdirManager.kt
packages/cli/src/main/resources/META-INF/native-image/resource-config.json
packages/cli/src/main/resources/elide.yml
packages/cli/src/main/resources/logback.xml
packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/NativeTransportFeature.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/server/http/HttpServerAgent.kt
packages/server/src/main/kotlin/elide/server/Application.kt
packages/server/src/main/kotlin/elide/server/cfg/ServerConfigurator.kt
pnpm-lock.yaml
samples/fullstack/react-ssr/server/src/main/kotlin/fullstack/reactssr/App.kt
tools/scripts/express.js

Omnibus package of hotfixes before `alpha7` release. This suite of fixes constitutes a bunch of individual bugfixes which, individually, don't really qualify for a full-blown PR, and must land before release (ideally). Merging as part of #445.
- fix: add `react` and `react-dom` dependencies
- fix: disable eager loading of native libs in cli tool
- fix: reduce default event-loop threads
- fix: startup-friendly server changes (don't eagerly init singletons)
- fix: initialize dispatcher at runtime (not statically)
- fix: include all jansi resources
- fix: logback configuration tweaks
- fix: native terminal init steps
- chore: general sample and import cleanup

Pre-release Hotfixes: `alpha7`

---

packages/cli/src/main/kotlin/elide/tool/cli/AbstractSubcommand.kt
packages/cli/src/main/resources/elide.yml

Enable virtual threads in Elide.
- feat: enable `VIRTUAL` threads in micronaut executors
- feat: enable `ofVirtual` threads in engine thread factory

Feature: Sicko Mode (Loom)

---

packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/core/HostRuntime.kt
packages/graalvm/src/main/kotlin/elide/runtime/core/PolyglotEngineConfiguration.kt
packages/graalvm/src/main/kotlin/elide/runtime/core/Version.kt
packages/graalvm/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMConfiguration.kt
packages/graalvm/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMEngine.kt
packages/graalvm/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMRuntime.kt
packages/graalvm/src/test/kotlin/elide/runtime/core/VersionTest.kt
packages/graalvm/src/test/kotlin/elide/runtime/core/internals/graalvm/GraalVMRuntimeTest.kt

This PR introduces the `HostRuntime` API, which provides information about the runtime to engine plugins. Use the `PolyglotEngineConfiguration.hostRuntime` property to access it:
```kotlin
/** Provides information about the runtime hosting the application. */
@DelicateElideApi public interface HostRuntime {
/** The name of this runtime, which is used in string representations and for debugging purposes. */
public val name: String
/** The version spec of this runtime, wrapped to allow version comparisons using regular operators. */
public val version: Version?
/** An optional variant name for this runtime. Some engines like GraalVM differentiate between runtime variants. */
public val variant: String?
}
```
The `HostRuntime.on` extension provides conditional execution of code based on the …

feat: new runtime info API

---

packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt
packages/cli/src/main/kotlin/elide/tool/project/DefaultProjectManager.kt
packages/graalvm-py/src/main/resources/META-INF/elide/embedded/runtime/python/environment.py
packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/core/PolyglotEngineConfiguration.kt
packages/graalvm/src/main/kotlin/elide/runtime/plugins/env/EnvConfig.kt
packages/graalvm/src/main/kotlin/elide/runtime/plugins/env/EnvPlugin.kt
packages/graalvm/src/main/kotlin/elide/runtime/plugins/js/JavaScript.kt

This PR updates the `Environment` plugin to remove dependencies on language plugins.
The env variables proxy is injected through polyglot bindings by default. Languages without support for polyglot bindings may install the env proxy manually to language-scoped bindings using `Environment.install(PolyglotContext, GuestLanguage)`.

feat: decouple env plugin from language runtimes

---

README.md

Adding support for installation of binary Elide through Homebrew. New directions added to README are tested on macOS:
```
brew tap elide-dev/elide
brew install elide
```
- chore: add homebrew install to readme

chore: add homebrew install to readme

---

tools/images/base/Dockerfile
tools/images/bash/Dockerfile
tools/images/bash/Makefile
tools/images/bash/cloudbuild.yaml
tools/images/elide/Dockerfile
tools/images/elide/Makefile
tools/images/elide/cloudbuild.yaml
tools/images/elide/entrypoint.sh

Adds two new containers produced by the Elide project:
- `ghcr.io/elide-dev/bash`: Bash terminal with Elide pre-installed.
- `ghcr.io/elide-dev/elide`: Direct use of Elide as a container entrypoint.
Use examples:
```
docker run --platform linux/amd64 --rm -it ghcr.io/elide-dev/bash
> elide --version
1.0.0-alpha7
```
```
docker run --platform linux/amd64 --rm -it ghcr.io/elide-dev/elide --version
1.0.0-alpha7
```

feat(dev): add `bash` and `elide` containers

---

packages/cli/src/main/kotlin/elide/tool/io/RuntimeWorkdirManager.kt

This PR solves the crash that happens when no `~/.elide` directory is present.
Fixes #469

fix(cli): avoid crashing when no user config directory is present.

---

.github/workflows/build.ci.yml

Adds the new [Buildless Github Action][0] to Elide's CI.
[0]: https://github.com/buildless/setup

chore: add buildless github action to ci

---

packages/graalvm/src/main/kotlin/elide/runtime/plugins/js/JavaScriptConfig.kt
packages/graalvm/src/test/kotlin/elide/runtime/plugins/js/JsCoreModulesTest.kt

This PR includes core module replacements in the JS plugin by default, and also adds tests for this behavior to avoid regressions.
Closes #458

fix(graalvm): include core module replacements by default in js plugin.

---

packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt
packages/cli/src/main/resources/META-INF/native-image/resource-config.json

This PR fixes a bug in native distributions of Elide, where the `nanorc` configuration directory would not be unpacked correctly due to missing resource configuration entries in the GraalVM native image metadata, breaking syntax highlighting on most machines (specifically, those devices where `$ELIDE_HOME/nanorc` was empty or didn't exist).
The issue was not obvious because the code that handled unpacking the default `nanorc` files skipped entries that were not present in the resources, without raising any errors or logging messages.
A new warning log has been added to prevent this in the future.
- fix(cli): add `nanorc` resources to `resources-config.json`.
- feat(cli): log a warning if a required `nanorc` configuration file is not found in the bundled resources.

fix(cli): correctly add nanorc resources to native image

---

Makefile

This PR adds the `runtime-build` and `runtime-update` targets to the root Makefile, which can be used to automatically refresh the JavaScript runtime facade and module bundles.
The make targets will run a Bazel build in the `runtime` directory (make sure the submodule is up to date), and the output for the relevant components will be packaged and copied to their destination in the project sources.

feat(makefile): add js runtime build targets

---

packages/graalvm-ts/api/graalvm-ts.api
packages/graalvm-ts/src/main/java/elide/runtime/lang/typescript/TypeScriptLanguage.java
packages/graalvm-ts/src/main/java/elide/runtime/lang/typescript/internals/TypeScriptCompiler.java
packages/graalvm-ts/src/main/kotlin/elide/runtime/plugins/typescript/TypeScript.kt
packages/graalvm-ts/src/test/kotlin/elide/runtime/lang/typescript/TypeScriptLanguageTest.kt
packages/graalvm/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMEngine.kt
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/sqlite/SqliteModule.kt
packages/graalvm/src/main/kotlin/elide/runtime/plugins/js/JavaScript.kt
packages/graalvm/src/main/kotlin/elide/runtime/plugins/js/JavaScriptConfig.kt
tools/scripts/hello.ts

Fixes TypeScript support from the entrypoint; fixes the TypeScript module patcher which allows for TypeScript-native imports.
- Fixes #910 
- Relates to #824 
- fix: typescript compiler and js realm/context use
- fix: invocation of typescript from entrypoint
- fix: module loader requires access to disk

fix: typescript support

---

.gitattributes
packages/graalvm/api/graalvm.api
packages/graalvm/detekt-baseline.xml
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/server/http/ExpressResponseAPI.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/server/http/HttpResponse.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/server/http/netty/NettyHttpResponse.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/server/http/netty/NettyRequestHandler.kt

Adds methods for emitting response headers from guest code. Improves support for the Express API.
- fix: header methods on response intrinsic
- fix: append `Date` header to responses if `includeDefaults` is `true`
- chore: re-pin `graalvm` module
- chore: update `graalvm` detekt baseline
- chore: more gitattribute fixes

fix: elide server response headers

---

settings.gradle.kts

There is no longer a `wrappers` project, which is confusing Sonar.

fix: dangling `wrappers` project (unused)

---

packages/runtime/src/config/resource-config-darwin-aarch64.json
packages/runtime/src/config/resource-config-darwin-amd64.json
packages/runtime/src/config/resource-config-linux-aarch64.json
packages/runtime/src/config/resource-config-linux-amd64.json
packages/runtime/src/config/resource-config-windows-aarch64.json
packages/runtime/src/config/resource-config-windows-amd64.json
packages/runtime/src/main/resources/META-INF/native-image/resource-config.json

Fixes missing resource mappings on non-macOS operating systems.
Fixes and closes elide-dev/elide#984

fix(runtime): jna on non-macOS operating systems

---

packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/AbstractStaticNativeLibraryFeature.kt
packages/runtime/build.gradle.kts
packages/runtime/detekt-baseline.xml
packages/runtime/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt
packages/runtime/src/main/resources/META-INF/native-image/jni-config.json
packages/runtime/src/main/resources/META-INF/native-image/proxy-config.json
packages/runtime/src/main/resources/META-INF/native-image/reflect-config.json
packages/runtime/src/main/resources/META-INF/native-image/resource-config.json
tools/scripts/cpu.js

Builds on top of #988 with a better suite of fixes on both macOS and Linux for OS info obtain via OSHI/JNA. Fixes and closes #990.
- fix: jna/oshi reflection and proxy metadata
- fix: no stacktrace for host-side error causes in native mode
- chore: cpu test script
- chore: update `graalvm` module pin / detekt baseline

fix: jna os info on linux/macos

---

packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/vfs/EmbeddedGuestVFSImpl.kt
packages/runtime/build.gradle.kts
packages/runtime/src/main/resources/META-INF/native-image/reflect-config.json

Fixes and closes elide-dev/elide#989.
- fix: cast error for `ino` attribute; should be `Long`
- fix: `-flto` breaks mac native build
- fix: missing vfs protobuf metadata

fix: cast err with python + embedded vfs

---

packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/AbstractStaticNativeLibraryFeature.kt
packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/NativeSQLiteFeature.kt
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/sqlite/SqliteModule.kt
packages/runtime/build.gradle.kts
packages/sqlite/build.gradle.kts
packages/sqlite/src/main/cpp/NativeDB.c
packages/sqlite/src/main/java/org/sqlite/SQLiteJDBCLoader.java
packages/sqlite/src/main/java/org/sqlite/core/NativeDB.java
packages/sqlite/src/main/java/org/sqlite/util/LibraryLoaderUtil.java

Fixes for SQLite that enable Static JNI access.
- fix: symbol collisions with `JNI_OnLoad`
- fix: JNI protocol version at `JNI_VERSION_1_8`

fix(sqlite): static jni for sqlite

---

packages/graalvm-ts/src/main/java/elide/runtime/lang/typescript/JSRealmPatcher.java
packages/graalvm-ts/src/main/java/elide/runtime/lang/typescript/TypeScriptLanguage.java

Fixes and closes elide-dev/elide#824, relating to the TypeScript module loader.
- fix: truffle boundary for native ts module loader
- chore: general typescript cleanup

fix(typescript): fixup ts module loader

---

packages/graalvm/detekt-baseline.xml
packages/graalvm/src/main/kotlin/elide/runtime/feature/engine/NativeSQLiteFeature.kt
packages/runtime/src/main/resources/META-INF/native-image/jni-config.json
packages/sqlite/src/main/cpp/NativeDB.c
packages/sqlite/src/main/java/org/sqlite/SQLiteJDBCLoader.java

Fixes for SQLite's static init code.
- fix(sqlite): guard static init so it cannot be run more than once
- fix(sqlite): universally use `JNI_VERSION_1_8`
- chore: better (manual) debug logs for sqlite native

fix(sqlite): static initialization

---

packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/events/CustomEvent.kt
packages/graalvm/src/main/kotlin/elide/runtime/node/events/NodeEvents.kt
packages/graalvm/src/test/kotlin/elide/runtime/intrinsics/js/JsGlobalsTest.kt
packages/graalvm/src/test/kotlin/elide/runtime/node/NodeEventsTest.kt

Fixes missing `CustomEvent` constructor; exposed by tests added in #1212.

fix: expose `CustomEvent` constructor

---

packages/engine/src/main/kotlin/elide/runtime/core/PolyglotContext.kt
packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/AbstractJsIntrinsic.kt
packages/graalvm/src/main/kotlin/elide/runtime/javascript/QueueMicrotaskCallable.kt
packages/graalvm/src/main/kotlin/elide/runtime/plugins/js/Extensions.kt
packages/graalvm/src/test/kotlin/elide/runtime/intrinsics/js/JsGlobalsTest.kt
packages/graalvm/src/test/kotlin/elide/runtime/javascript/QueueMicrotaskTest.kt

Name's on the tin. Closes #1265. 
```
- feat(graalvm): add support for `queueMicrotask`
- test(graalvm): tests for `queueMicrotask`
```

feat: add support for `queueMicrotask`

---

packages/cli/build.gradle.kts
packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json
packages/graalvm/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMEngine.kt

Fixes a crash at current release experienced when starting the main JS REPL. Closes #1270.

fix(cli): native image boot to repl

---

packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/gvm/js/JsError.kt
packages/graalvm/src/main/kotlin/elide/runtime/javascript/NavigatorBuiltin.kt
packages/graalvm/src/test/kotlin/elide/runtime/intrinsics/js/JsGlobalsTest.kt
packages/graalvm/src/test/kotlin/elide/runtime/winter/CommonMinimumTest.kt

Adds `navigator.userAgent` to the JS context.
- #1275

feat(graalvm): add support for `navigator.userAgent`

---

packages/engine/src/main/kotlin/elide/runtime/core/PluginRegistry.kt
packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/MessageChannel.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/MessagePort.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/Transferable.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/messaging/PostMessageOptions.kt
packages/graalvm/src/main/kotlin/elide/runtime/javascript/MessageChannelBuiltin.kt
packages/graalvm/src/main/kotlin/elide/runtime/javascript/MessagePortBuiltin.kt
packages/graalvm/src/main/kotlin/elide/runtime/node/events/NodeEvents.kt
packages/graalvm/src/test/kotlin/elide/runtime/javascript/MessageChannelTest.kt
packages/graalvm/src/test/kotlin/elide/runtime/winter/CommonMinimumTest.kt

Adds very basic support for [`MessageChannel`](https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel) and [`MessagePort`](https://developer.mozilla.org/en-US/docs/Web/API/MessagePort). These implementations dispatch their counterparts as expected, and new support is added to the Node events logic for accepting handlers (etc) at `on{event}` properties, but no cross-context dispatch is supported until reparenting `MessagePort` context is added later.
The intent is to get React 19 running, which requires these types (it's supposed to warn if they are missing, but that seems broken). We don't actually need any cross-context dispatch yet.
```
feat: add `MessageChannel` interface and basic impl
feat: add `MessagePort` interface and basic impl
test: add initial tests for channel …
```

feat: add support for `MessageChannel`

---

packages/cli/build.gradle.kts
packages/cli/src/main/kotlin/elide/tool/cli/cmd/discord/ToolDiscordCommand.kt

Prompt before opening links, e.g. to the Discord.
Fixes and closes elide-dev/elide#1335.

fix(cli): ask before opening links

---

packages/cli/build.gradle.kts
packages/cli/src/main/kotlin/elide/tool/cli/CommandContext.kt
packages/cli/src/main/kotlin/elide/tool/cli/Elide.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/tool/AbstractGenericTool.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/tool/DelegatedGenericToolCommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/tool/DelegatedToolCommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/tool/jar/JarTool.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/tool/javac/JavaCompiler.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/tool/javadoc/JavadocTool.kt
packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json
packages/engine/api/engine.api
packages/engine/src/main/kotlin/elide/tool/Argument.kt
packages/engine/src/main/kotlin/elide/tool/Outputs.kt
tools/scripts/Hello.java

Adds support for standard extra Java tools, including `javadoc` and `jar`.
```
feat(cli): implement `jar` tool support
feat(cli): implement `javadoc` tool support
```

feat(cli): support `javadoc` and `jar` tools

---

packages/cli/src/main/kotlin/elide/tool/cli/cmd/builder/ToolBuildCommand.kt
packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json

Fixes a reflection error that surfaces when using certain `java.util.Locale` methods.

fix: reflection err in locale constructor

---

packages/graalvm/build.gradle.kts

Gradle doesn't expose JAVA_HOME environment variable to exec tasks, which is required by the builder crate.
- fix: JAVA_HOME environment variable not passed on to cargo when building rust natives through gradle

fix: JAVA_HOME environment variable not passed on to cargo when building rust natives through gradle

---

packages/cli/src/main/kotlin/elide/tool/cli/AbstractSubcommand.kt
packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json

Fixes a `lateinit` property on `AbstractSubcommand` which was not present in reachability metadata. Telemetry should be disabled by default before Elide leaves beta anyway. Telemetry errors should also not cause a crash in any circumstance.
Fixes and closes elide-dev/elide#1425

fix: apply reachability metadata after telemetry changes

---

.github/workflows/checks.apicheck.yml
.github/workflows/checks.formatting.yml
.github/workflows/job.native-image.yml
settings.gradle.kts
tools/elide-build/settings.gradle.kts
tools/elide-build/src/main/kotlin/elide/internal/conventions/Constants.kt
tools/scripts/build-release-opt.sh

Allows overrides for `platform`, `version`, and `arch` values in the release script, which clears the way for automated snapshot releasing in GHA.

fix: release script overrides

---

packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json

Registers all Maven Model reflection metadata so that parsing POMs from dependencies doesn't cause issues in native mode. These sections aren't supported yet by Elide's foreign-manifests feature, but may be encountered in fetched dependency POMs.
- Fixes: elide-dev/elide#1487

fix: reflection issues with maven model

---

packages/cli/src/main/kotlin/elide/tool/cli/AbstractSubcommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/init/InitCommand.kt
packages/telemetry/api/telemetry.api
packages/telemetry/src/main/kotlin/elide/runtime/telemetry/TelemetryConfig.kt

Small conveniences and fixes for `elide init`.
```
fix: don't prompt about overwrite for empty dirs
chore: add `--yes` flag to `elide init`
chore: properly enforce `--force` flag
```

fix: `elide init` flags and conveniences

---

packages/graalvm/api/graalvm.api
packages/graalvm/build.gradle.kts
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/FilesystemAPI.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/FilesystemPromiseAPI.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/fs/Dir.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/fs/Dirent.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/fs/OpenDirOptions.kt
packages/graalvm/src/main/kotlin/elide/runtime/node/fs/Directory.kt
packages/graalvm/src/main/kotlin/elide/runtime/node/fs/DirectoryEntry.kt
packages/graalvm/src/main/kotlin/elide/runtime/node/fs/NodeFilesystem.kt
packages/graalvm/src/test/kotlin/elide/runtime/node/NodeFsPromisesTest.kt
packages/graalvm/src/test/kotlin/elide/runtime/node/NodeFsTest.kt

Adds support for `node:fs` methods `opendir`, `opendirSync`, and `promises/opendir`; such methods were blocked on implementation of the `fs.Dir` and `fs.Dirent` classes, which also were added.
```
feat(node): implement `fs.Dir`
feat(node): implement `fs.Dirent`
feat(node): implement `fs.opendir`
feat(node): implement `fs.opendirSync`
feat(node): implement `fs/promises.opendir`
test(node): tests for `fs.opendir` and friends
test(node): test for `fs/promises.opendir`
chore: update detekt baseline
```

feat(node): support for `fs.opendir[Sync]`

---

gradle/elide.versions.toml
packages/cli/build.gradle.kts
packages/cli/src/main/kotlin/elide/tool/cli/AbstractSubcommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/Elide.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/dev/LspCommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/dev/McpCommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/options/LspOptions.kt
packages/cli/src/main/kotlin/elide/tool/cli/options/McpOptions.kt
packages/cli/src/main/pkl/Dev.pkl
packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json
packages/engine/api/engine.api
packages/engine/src/main/kotlin/elide/runtime/core/PolyglotEngine.kt
packages/engine/src/main/kotlin/elide/runtime/plugins/AbstractLanguagePlugin.kt
packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMEngine.kt
packages/tooling/api/tooling.api
packages/tooling/src/main/kotlin/elide/tooling/project/manifest/ElidePackageManifest.kt

Adds simple entrypoints for `elide lsp` and `elide mcp`. LSP is pretty simple, and MCP only supports stdio for now (servers need Ktor). MCP is preloaded with access to the Elide project config, but not much else yet.
```
feat(cli): implement `elide lsp` command
feat(cli): implement `elide mcp` command
feat(cli): add lsp-specific options to cli
feat(cli): add mcp-specific options to cli
```

feat(cli): add `lsp` and `mcp` commands

---

.github/workflows/checks.detekt.yml

Restores `audit` mode for Detekt in CI, because something important is apparently getting blocked. It appears flaky because when Gradle (itself) is cached, there is no failure.

fix: restore `audit` mode for detekt checks

---

packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/QuerystringAPI.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/querystring/QueryParams.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/querystring/QuerystringOptions.kt
packages/graalvm/src/main/kotlin/elide/runtime/node/querystring/NodeQuerystring.kt
packages/graalvm/src/test/kotlin/elide/runtime/node/NodeQuerystringTest.kt

First pass at implementing Node's [`querystring`](https://nodejs.org/docs/latest/api/querystring.html) module.

feat: implement node `querystring`

---

Cargo.toml

Reduces our optimization level in Rust land, and forces `trace`, `exec`, and `umbrella` to build in "small" mode; this fixes a native crash (for unclear reasons) related to Orogene, tracing, and Elide's builder. The crash warrants further investigation, but, for now, this is a release blocker, so we have a WA.
- Fixes and closes elide-dev/elide#1554

fix: macos hard-crash related to tracing

---

packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json
packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/fetch/FetchHeadersIntrinsic.kt
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/fetch/FetchIntrinsic.kt

Fixes crash via use of `new Headers()`, because of missing reachability metadata.
- Fixes: elide-dev/elide#1559

fix(cli): reachability metadata for fetch headers

---

packages/cli/src/main/kotlin/elide/tool/cli/AbstractToolCommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/HandledExit.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/main.kt
packages/cli/src/main/kotlin/elide/tool/err/ErrorHandler.kt
third_party/oracle/README.md

Restores pretty error handling. Given the script,
```js
console.log("hi", missing)
```
And,
```
elide run ./err.js
```
Before this PR:
```
Uncaught fatal exception: org.graalvm.polyglot.PolyglotException: ReferenceError: missing is not defined
<js>.:program(err.js:1)
org.graalvm.polyglot/org.graalvm.polyglot.Value.execute(Value.java:1047)
elide.tool.cli.cmd.repl.ToolShellCommand.execWrapped(ToolShellCommand.kt:1656)
elide.tool.cli.cmd.repl.ToolShellCommand.executeSource(ToolShellCommand.kt:1870)
elide.tool.cli.cmd.repl.ToolShellCommand.invoke$lambda$191$lambda$174(ToolShellCommand.kt:2808)
elide.tool.cli.AbstractSubcommand.withDeferredContext(AbstractSubcommand.kt:686)
elide.tool.cli.AbstractSubcommand.withDeferredContext$default(AbstractSubcommand
... …
```

fix: guest error handling (js)

---

packages/builder/api/builder.api
packages/builder/build.gradle.kts
packages/builder/src/main/kotlin/elide/tooling/cli/Statics.kt
packages/builder/src/main/kotlin/elide/tooling/kotlin/KotlinCompiler.kt
packages/cli/detekt-baseline.xml
packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt
packages/cli/src/main/resources/nanorc/jnanorc
packages/cli/src/main/resources/nanorc/kotlin.nanorc
packages/tooling/api/tooling.api
packages/tooling/build.gradle.kts
packages/tooling/src/main/kotlin/elide/tooling/term/TerminalUtil.kt

Adds syntax highlighting, via our REPL tools, for code emitted in other circumstances by the CLI.
| **Before** | **After** |
| ----------- | ---------- |
| <img alt="image" src="https://github.com/user-attachments/assets/9142db2a-464d-4968-a973-81b51e29c975" /> | <img alt="Screenshot 2025-07-26 162623" src="https://github.com/user-attachments/assets/82fb55e4-071b-4ff7-ab26-7a542dc21c85" /> |
| <img alt="image" src="https://github.com/user-attachments/assets/5bb8f783-28fb-4345-955c-1948c80e1425" /> | <img alt="image" src="https://github.com/user-attachments/assets/50092fa2-5003-4d8f-b422-5ea19763aeb3" /> |

feat: highlighting for error context

---

crates/web/src/css.rs

fix: add explicit lifetime parameters to build_printer_options and css_options function signatures
This removes "mistmatched lifetime syntax" warnings.
- fix: add explicit lifetime parameters to build_printer_options and css_options function signatures

fix: add explicit lifetime parameters to build_printer_options and css_options function signatures

---

packages/cli/src/main/kotlin/elide/tool/cli/options/EngineJavaScriptOptions.kt
packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/js/JsTimers.kt
packages/graalvm/src/main/kotlin/elide/runtime/gvm/intrinsics/BuildTimeIntrinsicsResolver.kt
packages/graalvm/src/main/kotlin/elide/runtime/javascript/BrowserStubs.kt
packages/graalvm/src/main/kotlin/elide/runtime/plugins/js/JavaScript.kt
packages/graalvm/src/main/kotlin/elide/runtime/plugins/js/JavaScriptConfig.kt

Adds necessary support infra to be able to run [`js-benchmarks`](https://github.com/elide-dev/js-benchmarks) on Elide.

fix: `--js:strict` and benchmark symbols

---

packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt
packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/node/ProcessAPI.kt
packages/graalvm/src/main/kotlin/elide/runtime/node/process/NodeProcess.kt
packages/graalvm/src/main/kotlin/elide/runtime/plugins/env/EnvPlugin.kt
packages/graalvm/src/test/kotlin/elide/runtime/gvm/internals/AbstractDualTest.kt
packages/graalvm/src/test/kotlin/elide/runtime/node/NodeProcessTest.kt
packages/graalvm/src/test/kotlin/elide/runtime/plugins/EnvPluginTest.kt

This PR adds a couple of fixes related to host environment variable access from guest code:
Node's `process.env` now returns the environment map installed by the `Environment` plugin, which correctly enforces host access configuration and supports loading `.env` files, etc. This fixes #1664, which was not a failure of the env map itself, but instead an issue with formatting when writing to console or using `JSON.stringify`
Additionally, Node `process` tests now verify that `env` matches the map installed by the env plugin instead of checking against host env directly. Tests have been added to verify that the `Environment` plugin correctly handles host access settings.

fix: enforce host environment access rules and correct process.env formatting

---

packages/cli/src/main/kotlin/elide/tool/cli/AbstractSubcommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/dev/LspCommand.kt
packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt
packages/engine/api/engine.api
packages/engine/src/main/kotlin/elide/runtime/core/PolyglotEngine.kt
packages/graalvm/api/graalvm.api
packages/graalvm/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMEngine.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/server/http/internal/PipelineRouter.kt
packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/server/http/netty/NettyHttpResponse.kt
packages/http/api/http.api
packages/http/src/commonMain/kotlin/elide/http/DefaultUrlParams.kt
packages/http/src/commonMain/kotlin/elide/http/Params.kt

This PR fixes #1670 and restores minimal functionality to Elide's HTTP server intrinsics:
- New GraalVM `Context` instances are now correctly attached to an `Engine`. This behavior is disabled by default when acquiring a new context from a CLI command using `resolvePolyglotContext()`, to avoid breaking existing code; it can be enabled by passing `detached = false`.
- The `NettyHttpResponse.from(...)` builder function now returns a new empty mutable response; it was previously unimplemented.
In general, the `serve` command should now work again, though some features are still unimplemented (coming soon). 
> [!IMPORTANT]
> The old `express` intrinsics are no longer available, `Elide.http` should be used instead. Support for express-like APIs and a drop-in express.js replacement may be added …

fix: crash on http server use
