elide-dev/elide

gradle.properties, gradle/verification-metadata.xml, packages/base/src/commonMain/kotlin/elide/AppEnvironment.kt, packages/graalvm/src/main/kotlin/elide/runtime/graalvm/JsRuntime.kt, packages/graalvm/src/main/kotlin/elide/runtime/graalvm/JsRuntimeTypes.kt, packages/graalvm/src/main/kotlin/elide/server/SSRExtensions.kt, packages/graalvm/src/main/kotlin/elide/server/ssr/ServerSSRRenderer.kt, packages/model/build.gradle.kts, packages/server/src/main/kotlin/elide/server/Application.kt, packages/server/src/main/kotlin/elide/server/ResponseExtensions.kt, packages/server/src/main/kotlin/elide/server/runtime/AppExecutor.kt, packages/server/src/main/kotlin/elide/server/util/ServerFlag.kt, packages/server/src/main/kotlin/kotlinx/html/api.ext.kt, packages/server/src/main/kotlin/kotlinx/html/tagext/tags.ext.kt, packages/server/src/main/kotlin/kotlinx/html/tagsgen.ext.kt, samples/fullstack/basic/server/src/main/kotlin/fullstack/basic/App.kt, samples/fullstack/react-ssr/server/build.gradle.kts, samples/fullstack/react-ssr/server/src/main/kotlin/fullstack/reactssr/App.kt, samples/fullstack/react-ssr/server/src/main/resources/logback.xml, samples/fullstack/react/server/src/main/kotlin/fullstack/react/App.kt, samples/fullstack/ssr/server/src/main/kotlin/fullstack/ssr/App.kt, samples/server/hellocss/src/main/kotlin/hellocss/App.kt, samples/server/helloworld/src/main/kotlin/helloworld/App.kt
This changeset introduces a refactor of the GraalVM `JsRuntime` which should cut warmup and subsequent request latency and throughput via some low-hanging optimizations. Details forthcoming.
=> Feature: JS Runtime v2

packages/cli/build.gradle.kts, packages/ssg/build.gradle.kts, samples/fullstack/basic/server/build.gradle.kts, samples/fullstack/react-ssr/server/build.gradle.kts, samples/fullstack/react/server/build.gradle.kts, samples/fullstack/ssr/server/build.gradle.kts, samples/server/hellocss/build.gradle.kts, samples/server/helloworld/build.gradle.kts, settings.gradle.kts, site/docs/app/build.gradle.kts, tools/bundler/build.gradle.kts
Sets up build caching to work efficiently.
=> Chore: Build Caching

.github/workflows/build.ci.yml
Fixes push to build cache from CI
=> chore: fix build cache push from ci build

gradle.properties, gradle/elide.versions.toml, kotlin-js-store/yarn.lock, packages/cli/build.gradle.kts, packages/cli/src/main/kotlin/elide/tool/cli/ElideTool.kt, packages/cli/src/main/kotlin/elide/tool/cli/Statics.kt, packages/cli/src/main/kotlin/elide/tool/cli/cmd/AbstractSubcommand.kt, packages/cli/src/main/kotlin/elide/tool/cli/cmd/express/ToolExpressCommand.kt, packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt, packages/cli/src/main/resources/META-INF/native-image/jni-config.json, packages/cli/src/main/resources/META-INF/native-image/reflect-config.json, packages/cli/src/main/resources/META-INF/native-image/resource-config.json, packages/cli/src/main/resources/elide.yml, packages/cli/src/main/resources/logback.xml, packages/graalvm/api/graalvm.api, packages/graalvm/build.gradle.kts, packages/graalvm/src/main/kotlin/elide/runtime/feature/js/JsRuntimeFeature.kt, packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressAppIntrinsic.kt, packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressContext.kt, packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressIntrinsic.kt, packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressRequestIntrinsic.kt, packages/graalvm/src/main/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressResponseIntrinsic.kt, packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/express/Express.kt, packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/express/ExpressApp.kt, packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/express/ExpressRequest.kt, packages/graalvm/src/main/kotlin/elide/runtime/intrinsics/js/express/ExpressResponse.kt, packages/graalvm/src/test/kotlin/elide/runtime/gvm/internals/intrinsics/js/express/ExpressIntrinsicTest.kt, packages/server/build.gradle.kts, tools/conventions/src/main/kotlin/GraalVMVersions.kt
> **Warning**
> This support is experimental.
This PR opens experimental work on an Express.js-compatible API for Elide, usable through a new command in the CLI. Express support is very early and only provides a couple of very simple methods, as a proof of concept. Support for the entire API may be added later in order to allow a smooth migration of Express-based apps to Elide.
- #319 
- elide-dev/runtime#190
=> labs: express intrinsics and CLI support

settings.gradle.kts
This PR updates the root build scripts to allow disabling remote cache push using Gradle configuration properties present in the local environment.
=> chore: allow disabling remote cache push

.editorconfig
This PR updates the root `.editorconfig` file to fix issues with annotation wrapping in Kotlin.
- disable annotation wrapping in Kotlin
- remove redundant rules
=> chore: code style maintenance

gradle/elide.versions.toml, packages/cli/build.gradle.kts, packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt
Add a summary about your PR here.
**Related issues:**
- #394
- oracle/graal#7110
- micronaut-projects/micronaut-core#9664
- fix: missing `log4j` classes, via `slf4j` bridge
- fix: allow conditional language inclusion in `cli` build
- fix: drop JRT flag to `native-image`
- fix: swap to `NONE` runtime for Micronaut
- fix: missing `initialize-at-build-time` netty types
- fix: missing Netty, NPN, ALPN dependencies
- chore: ability to dynamically load/detect languages in cli
=> fix: native-image jit linkage errors in `cli`

.github/ISSUE_TEMPLATE/bug_report.yaml
- feat: addressable field IDs
- feat: markdown support in `expected` and `actual` fields
- chore: better `env_info`
=> chore: update `bug_report` template

packages/cli/build.gradle.kts, packages/proto/proto-capnp/build.gradle.kts, packages/proto/proto-core/build.gradle.kts, packages/proto/proto-protobuf/build.gradle.kts, tools/elide-build/build.gradle.kts, tools/elide-build/src/main/kotlin/elide/internal/conventions/ElideBuildExtension.kt, tools/elide-build/src/main/kotlin/elide/internal/conventions/ElideConventionPlugin.kt, tools/elide-build/src/main/kotlin/elide/internal/conventions/jvm/JavaConventions.kt, tools/elide-build/src/main/kotlin/elide/internal/conventions/kotlin/KotlinConventions.kt, tools/elide-build/src/main/kotlin/elide/internal/conventions/native/NativeBuildConventions.kt, tools/elide-build/src/main/kotlin/elide/internal/conventions/publishing/PublishingConventions.kt
- fix(build): allow disabling graalvm toolchain resolution.
- fix(build): correct configuration of javadoc and sources jar tasks.
=> fix: internal build plugin fixes

packages/cli/src/main/kotlin/elide/tool/cli/cmd/repl/ToolShellCommand.kt, packages/runtime-core/api/runtime-core.api, packages/runtime-core/src/main/kotlin/elide/runtime/core/extensions/EngineBuilder.kt, packages/runtime-core/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMEngine.kt, packages/runtime-core/src/main/kotlin/elide/runtime/plugins/debug/DebugConfig.kt, packages/runtime-core/src/main/kotlin/elide/runtime/plugins/debug/DebugPlugin.kt
=> fix: debugger and inspector configuration

packages/runtime-core/src/main/kotlin/elide/runtime/core/internals/graalvm/GraalVMEngine.kt, packages/runtime-core/src/main/kotlin/elide/runtime/plugins/debug/DebugConfig.kt, packages/runtime-core/src/main/kotlin/module-info.java
More fixes for engine initialization in `runtime-core` (and other minor fixes).
=> fix: polyglot engine configuration options.

CONTRIBUTING.md
This PR adds the CONTRIBUTING.MD document.
=> chore: add contribution guidelines.

packages/cli/package.json, packages/cli/packaging/install-debug.sh, packages/cli/packaging/install.sh, packages/cli/packaging/npm/elide.js, packages/cli/packaging/npm/elide.sh, packages/cli/packaging/npm/package.json
Update CLI installation scripts to use the latest release.
=> chore: update install scripts.

packages/cli/package.json, packages/cli/packaging/npm/package.json
This PR corrects the changes introduced by #435 which caused yarn install to fail.
=> fix(cli): amend version for cli npm package

.github/FUNDING.yml
Adds Elide's new Patreon page to our GitHub Sponsorships configuration. Merging as part of #445.
- chore: add patreon
=> chore: add patreon

.devcontainer/Elide.dockerfile, .devcontainer/elide.devcontainer.json
Adds a Codespace template for trying out Elide as a runtime, rather than developing on Elide.
=> feat(dev): add codespace template for trying elide

.github/workflows/build.ci.yml, settings.gradle.kts, tools/plugin/gradle-plugin/plugin-build/settings.gradle.kts, tools/plugin/gradle-plugin/settings.gradle.kts, tools/substrate/buildSrc/settings.gradle.kts, tools/substrate/settings.gradle.kts
Updates to Buildless plugins and tooling.
- chore: upgrade buildless plugin → `1.0.0-beta8`
- chore: add buildless action to ci
=> chore: buildless updates

.github/workflows/checks.apicheck.yml, .github/workflows/job.cli.yml, .gitmodules, Cargo.toml, gradle.properties, gradle/verification-metadata.xml, packages/cli/packaging/install-debug.sh, packages/cli/packaging/install.sh, packages/graalvm/build.gradle.kts, packages/server/build.gradle.kts, packages/server/src/main/kotlin/elide/server/runtime/jvm/SecurityProviderConfigurator.kt, settings.gradle.kts, tools/bench/js.mjs, tools/scripts/build-release-debug.sh, tools/scripts/build-release-opt.sh
Fixes some distribution script issues experienced during the release of `alpha11`.
=> fix: dist issues with `alpha11`

packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json
=> fix: registration of logging bundle

.github/workflows/job.native-image.yml, packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json, packages/cli/src/projects/containers-jvm/.gitignore, packages/cli/src/projects/containers-jvm/elide.pkl, packages/cli/src/projects/containers-jvm/src/main/kotlin/sample/main.kt, packages/cli/src/projects/containers-jvm/src/test/kotlin/sample/testGreeting.kt, packages/cli/src/projects/containers/elide.pkl, tools/scripts/build-release-opt.sh
Release fixes, plus container reflection fixes on macOS.
=> fix: reflection for container builder/release config

project/website/elide.pkl, project/website/package-lock.kdl, project/website/src/global.mts, project/website/src/global.scss, project/website/src/home.scss, project/website/src/index.md, project/website/src/jobs.md, project/website/src/team.md, project/website/wrangler.toml
Adds a simple website for Elide, built by Elide. See it live at [`elide.dev`](https://elide.dev).
=> chore: simple elide-built website

packages/builder/src/main/kotlin/elide/tooling/jvm/JavaCompiler.kt, packages/cli/src/main/kotlin/elide/tool/cli/cmd/tool/nativeImage/NativeImageAdapter.kt, packages/cli/src/main/resources/META-INF/native-image/dev/elide/elide-cli/reachability-metadata.json
Fixes a few issues discovered in `elide kotlinc` and `elide native-image`.
- Fixes #1689 
- Fixes #1688 
- Fixes #1687 
- Fixes #1686
=> fix: kotlinc/native-image bugs
